
import java.io.File;

import javax.swing.JFileChooser;

/**
 *
 * @author LUIS
 */
public class CpuUI extends javax.swing.JFrame {

    private Simulator simulator = new Simulator();
    final JFileChooser fc = new JFileChooser();

    /**
     * Creates new form CpuUI
     */
    public CpuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pcLabel = new javax.swing.JLabel();
        pcField = new javax.swing.JTextField();
        irField = new javax.swing.JTextField();
        irLabel = new javax.swing.JLabel();
        r0Label = new javax.swing.JLabel();
        r1Label = new javax.swing.JLabel();
        r2Label = new javax.swing.JLabel();
        r3Label = new javax.swing.JLabel();
        r4Label = new javax.swing.JLabel();
        r5Label = new javax.swing.JLabel();
        r6Label = new javax.swing.JLabel();
        r7Label = new javax.swing.JLabel();
        r0Field = new javax.swing.JTextField();
        r1Field = new javax.swing.JTextField();
        r3Field = new javax.swing.JTextField();
        r2Field = new javax.swing.JTextField();
        r4Field = new javax.swing.JTextField();
        r5Field = new javax.swing.JTextField();
        r6Field = new javax.swing.JTextField();
        r7Field = new javax.swing.JTextField();
        keyboardLabel = new javax.swing.JLabel();
        asciiLabel = new javax.swing.JLabel();
        hexLabel = new javax.swing.JLabel();
        parInLabel = new javax.swing.JLabel();
        parOutLabel = new javax.swing.JLabel();
        memoryLabel = new javax.swing.JLabel();
        keyboardField = new javax.swing.JTextField();
        asciiField = new javax.swing.JTextField();
        hexField = new javax.swing.JTextField();
        parInField = new javax.swing.JTextField();
        parOutField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoryArea = new javax.swing.JTextArea();
        addressBusLabel = new javax.swing.JLabel();
        controlBusLabel = new javax.swing.JLabel();
        dataBusLabel = new javax.swing.JLabel();
        controlBusField = new javax.swing.JTextField();
        addressBusField = new javax.swing.JTextField();
        dataBusField = new javax.swing.JTextField();
        condBitLabel = new javax.swing.JLabel();
        condBitField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //Set labels
        pcLabel.setText("PC");
        irLabel.setText("IR");
        r0Label.setText("R0");
        r1Label.setText("R1");
        r2Label.setText("R2");
        r3Label.setText("R3");
        r4Label.setText("R4");
        r5Label.setText("R5");
        r6Label.setText("R6");
        r7Label.setText("R7");
        keyboardLabel.setText("Keyboard");
        asciiLabel.setText("ASCII");
        hexLabel.setText("Hex");
        parInLabel.setText("Par IN");
        parOutLabel.setText("Par OUT");
        memoryLabel.setText("Memory");
        addressBusLabel.setText("Address Bus");
        controlBusLabel.setText("Control Bus");
        dataBusLabel.setText("Data Bus");
        condBitLabel.setText("Cond Bit");
        
        //Set menu bar and actions menu
        setJMenuBar(jMenuBar1);
        jMenuBar1.add(jMenu1);
        jMenu1.setText("Actions");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        
        //Add actions to menu
        jMenu1.add(jMenuItem5);
        jMenuItem5.setText("Load");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        
        jMenu1.add(jMenuItem2);
        jMenuItem2.setText("Stop");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        
        jMenu1.add(jMenuItem6);
        jMenuItem6.setText("Step");


        

        
        
        

        
        
        

        
        

        

        

        memoryArea.setColumns(20);
        memoryArea.setRows(5);
        jScrollPane1.setViewportView(memoryArea);

        pcField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        
        r1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        r3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        r4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        
        keyboardField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        asciiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });







        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(r0Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(r1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hexLabel)
                                    .addComponent(parInLabel))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parInField)
                                    .addComponent(hexField)
                                    .addComponent(parOutField, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(condBitLabel)
                                    .addComponent(dataBusLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcLabel)
                                    .addComponent(irLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pcField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(irField))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keyboardLabel)
                                    .addComponent(asciiLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asciiField)
                                    .addComponent(keyboardField))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(controlBusLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addressBusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(controlBusField)
                            .addComponent(dataBusField)
                            .addComponent(addressBusField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(condBitField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(r7Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(r7Field))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(r6Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(r6Field))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(r5Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(r5Field))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r2Label)
                                        .addComponent(r3Label)
                                        .addComponent(r4Label))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r4Field)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(r3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 1, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(r2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(memoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(parOutLabel))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcLabel)
                            .addComponent(pcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keyboardLabel)
                            .addComponent(keyboardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(asciiLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(irField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(irLabel)))
                            .addComponent(asciiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0Label)
                            .addComponent(r0Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hexLabel)
                            .addComponent(hexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1Label)
                            .addComponent(r1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parInLabel)
                            .addComponent(parInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condBitLabel)
                            .addComponent(condBitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r2Label)
                            .addComponent(r2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parOutLabel)
                            .addComponent(parOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(controlBusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(controlBusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressBusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressBusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataBusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataBusLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r3Label)
                            .addComponent(r3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r4Label)
                            .addComponent(r4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r5Label)
                            .addComponent(r5Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r6Label)
                            .addComponent(r6Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r7Label)
                            .addComponent(r7Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setVisible(true);
    }// </editor-fold>                        

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                      

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                           

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                           

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                            

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                            

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
    }                                           

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
    }  
    
    //Load Action Performed
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
    	int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            simulator.loadRegister(file);
            setFieldText();
        } else {
            System.out.append("Open command cancelled by user.\n");
        }
    }
    
    private void setFieldText(){
    	memoryArea.setText(simulator.getMemoryContents());
    	r0Field.setText(simulator.getRegisterContents("0"));
    	r1Field.setText(simulator.getRegisterContents("1"));
    	r2Field.setText(simulator.getRegisterContents("2"));
    	r3Field.setText(simulator.getRegisterContents("3"));
    	r4Field.setText(simulator.getRegisterContents("4"));
    	r5Field.setText(simulator.getRegisterContents("5"));
    	r6Field.setText(simulator.getRegisterContents("6"));
    	r7Field.setText(simulator.getRegisterContents("7"));
    	irField.setText(simulator.getRegisterContents("IR"));
    	pcField.setText(simulator.getRegisterContents("PC"));
    	
    	keyboardField.setText(simulator.getKeyboard());
    	parInField.setText(simulator.getParIn());
    	parOutField.setText(simulator.getParOut());
    	asciiField.setText(simulator.getAscii());
    	hexField.setText(simulator.getHex());
    	
    	addressBusField.setText(simulator.getAddressBus());
    	dataBusField.setText(simulator.getDataBus());
    	controlBusField.setText(simulator.getControlBus());
    	condBitField.setText(simulator.getCondBit());
    	
    }


    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel pcLabel; //PC
    private javax.swing.JLabel r7Label; //R7
    private javax.swing.JLabel keyboardLabel; //Keybo
    private javax.swing.JLabel asciiLabel; //ASCII
    private javax.swing.JLabel hexLabel; //Hex
    private javax.swing.JLabel parInLabel; //Par in
    private javax.swing.JLabel parOutLabel; //Par out
    private javax.swing.JLabel memoryLabel; //Mem
    private javax.swing.JLabel addressBusLabel; //Address
    private javax.swing.JLabel controlBusLabel; //Control 
    private javax.swing.JLabel dataBusLabel; // Data bus
    private javax.swing.JLabel irLabel;  //IR
    private javax.swing.JLabel condBitLabel; //Cond bit
    private javax.swing.JLabel r0Label; //R0
    private javax.swing.JLabel r1Label; //R1
    private javax.swing.JLabel r2Label; //R2
    private javax.swing.JLabel r3Label; //R3
    private javax.swing.JLabel r4Label; //R4
    private javax.swing.JLabel r5Label; //R5
    private javax.swing.JLabel r6Label; //R6
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1; //Menu Bar
    private javax.swing.JMenuItem jMenuItem2; //Stop
    private javax.swing.JMenuItem jMenuItem5; //Load
    private javax.swing.JMenuItem jMenuItem6; //Step
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memoryArea; //Memory
    private javax.swing.JTextField pcField;
    private javax.swing.JTextField r7Field;
    private javax.swing.JTextField keyboardField;
    private javax.swing.JTextField asciiField;
    private javax.swing.JTextField hexField;
    private javax.swing.JTextField parInField;
    private javax.swing.JTextField parOutField;
    private javax.swing.JTextField controlBusField;
    private javax.swing.JTextField addressBusField;
    private javax.swing.JTextField dataBusField;
    private javax.swing.JTextField condBitField;
    private javax.swing.JTextField irField;
    private javax.swing.JTextField r0Field;
    private javax.swing.JTextField r1Field;
    private javax.swing.JTextField r3Field;
    private javax.swing.JTextField r2Field;
    private javax.swing.JTextField r4Field;
    private javax.swing.JTextField r5Field;
    private javax.swing.JTextField r6Field;
    // End of variables declaration                   
}
